### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by RogerCreasy**
I failed to add a license when I initiated this project. My intent has been for this to be open for anyone to use and contribute.

I am placing this as a PR in order to give contributors a chance to disagree. If I hear an OK from all contributors, I will commit this license. If I do not hear from all contributors by October 23, I will assume an OK from anyone who does not explicitly give their OK. I will make a reasonable attempt to contact contributors.

### CODE REVIEW

**Comment by owenvoke** [comment]
Fine with me. 😄

**Comment by daanvanham** [comment]
OK 👍

**Comment by raavanan** [comment]
A ok 👍 

Thanks for the opportunity. this was my first PR. now that I have the initial fear and doubts cleared. i am regularly contributing to open source projects and its so gratifying to contribute to open source projects.

**Comment by GaryLeutheuser** [comment]
Good by me! :)

**Comment by matteo-hertel** [comment]
Absolutely fine by me!

**Comment by kartik95** [comment]
Fine with me! :)

**Comment by htadg** [comment]
Fine by me..

**Comment by RogerCreasy** [comment]
Thanks all! And, thanks for participating.

**Pull request merged**
