### PR TITLE
Add a check for the MSIE user agent

### PR DESCRIPTION
**Pull request by chrisonntag**
This PR adds a function which checks if the used browser is MSIE and returns its version number. It also checks for Microsofts try to fool user agent parsers in Internet Explorer 11.

### CODE REVIEW

**Comment by chrisonntag** [comment]
referencing issue #1

**Comment by owenvoke** [comment]
Tested this.
https://jsfiddle.net/PXgamer/tna683t5/

It works in _IE 9 & 10_.
In _IE 11_, it returns **0**. (not matching `/Trident\/7\./`)
In _Edge_ it returns **11**.
In _Chrome_, it returns **11**.
In _Firefox_, it also returns **11**.

As far as I can tell, there could be an issue with IE 11's spoofing.
My user agent for IE 11 is:
`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`
Which does contain `Trident/7.0` so I think the IE11 bit could be wrong?

**Comment by owenvoke** [comment]
Awesome. Works great now. 😄 
https://jsfiddle.net/PXgamer/tna683t5/2/

**Comment by RogerCreasy** [comment]
Thanks @chrisonntag and @PXgamer 
I am going to open an issue for getting this into the Readme

**Pull request merged**
